#!/usr/bin/env python3
"""Full pipeline integration test with 10 different configurations.

This script tests the spectral_select library end-to-end with the Lichens dataset,
using 20 epochs for fast training and 10 different configuration combinations.

Note: Uses pickle for data loading as this is the established format in the codebase.
The pickle files are generated by trusted preprocessing scripts.
"""

import logging
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple
from unittest.mock import patch

import numpy as np
import torch

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from spectral_select import Analyzer, Config
from spectral_select.types import SpectraData


# =============================================================================
# Configuration combinations to test
# =============================================================================

def get_test_configurations() -> List[Dict[str, Any]]:
    """Generate 10 different configuration combinations."""
    configs = [
        # Config 1: Default baseline
        {
            "name": "baseline_default",
            "dimension_selection_method": "activation",
            "perturbation_method": "percentile",
            "normalization_method": "variance",
            "n_bands_to_select": 20,
            "use_diversity_constraint": False,
        },
        # Config 2: Variance-based dimension selection
        {
            "name": "variance_selection",
            "dimension_selection_method": "variance",
            "perturbation_method": "percentile",
            "normalization_method": "variance",
            "n_bands_to_select": 20,
            "use_diversity_constraint": False,
        },
        # Config 3: PCA dimension selection
        {
            "name": "pca_selection",
            "dimension_selection_method": "pca",
            "perturbation_method": "percentile",
            "normalization_method": "variance",
            "n_bands_to_select": 20,
            "use_diversity_constraint": False,
        },
        # Config 4: Standard deviation perturbation
        {
            "name": "stddev_perturbation",
            "dimension_selection_method": "activation",
            "perturbation_method": "standard_deviation",
            "normalization_method": "variance",
            "n_bands_to_select": 20,
            "use_diversity_constraint": False,
        },
        # Config 5: Absolute range perturbation
        {
            "name": "absrange_perturbation",
            "dimension_selection_method": "activation",
            "perturbation_method": "absolute_range",
            "normalization_method": "variance",
            "n_bands_to_select": 20,
            "use_diversity_constraint": False,
        },
        # Config 6: Max per excitation normalization
        {
            "name": "max_normalization",
            "dimension_selection_method": "activation",
            "perturbation_method": "percentile",
            "normalization_method": "max_per_excitation",
            "n_bands_to_select": 20,
            "use_diversity_constraint": False,
        },
        # Config 7: No normalization
        {
            "name": "no_normalization",
            "dimension_selection_method": "activation",
            "perturbation_method": "percentile",
            "normalization_method": "none",
            "n_bands_to_select": 20,
            "use_diversity_constraint": False,
        },
        # Config 8: MMR diversity constraint
        {
            "name": "mmr_diversity",
            "dimension_selection_method": "activation",
            "perturbation_method": "percentile",
            "normalization_method": "variance",
            "n_bands_to_select": 20,
            "use_diversity_constraint": True,
            "diversity_method": "mmr",
            "lambda_diversity": 0.5,
        },
        # Config 9: Min distance diversity
        {
            "name": "min_distance_diversity",
            "dimension_selection_method": "activation",
            "perturbation_method": "percentile",
            "normalization_method": "variance",
            "n_bands_to_select": 20,
            "use_diversity_constraint": True,
            "diversity_method": "min_distance",
            "min_distance_nm": 20.0,
        },
        # Config 10: Comprehensive - best expected combo
        {
            "name": "comprehensive",
            "dimension_selection_method": "activation",
            "perturbation_method": "percentile",
            "normalization_method": "variance",
            "n_bands_to_select": 30,
            "n_important_dimensions": 20,
            "use_diversity_constraint": True,
            "diversity_method": "mmr",
            "lambda_diversity": 0.3,
        },
    ]
    return configs


# =============================================================================
# Patched training function with configurable epochs
# =============================================================================

def patched_train_new_model(self, num_epochs: int = 20) -> None:
    """Patched version of _train_new_model with configurable epochs.

    Uses 20 epochs by default for fast testing.
    """
    logger.warning(
        f"Training new autoencoder model with {num_epochs} epochs (fast test mode)..."
    )

    from scripts.models.training import train_with_masking

    # Determine output directory for training
    if self._config.output_dir is not None:
        train_output_dir = self._config.output_dir / "model_training"
    else:
        train_output_dir = Path("model_output")

    # Get mask from dataset
    mask = self._dataset.processed_mask

    # Train with fast test epochs
    self._model, losses = train_with_masking(
        model=self._model,
        dataset=self._dataset,
        num_epochs=num_epochs,  # Using fast test epochs
        learning_rate=0.001,
        device=str(self._device),
        mask=mask,
        output_dir=str(train_output_dir),
        verbose=True,
    )

    # Move to device and set to evaluation mode
    self._model = self._model.to(self._device)
    self._model.train(False)

    # Save model if path specified
    model_path = self._config.model_path
    if model_path is not None:
        model_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(self._model.state_dict(), model_path)
        logger.info(f"Model saved to {model_path}")

    logger.info(
        f"Model training complete. Final loss: {losses[-1]:.6f}"
    )


# =============================================================================
# Result evaluation
# =============================================================================

def evaluate_results(results: List[Dict[str, Any]]) -> None:
    """Evaluate and compare results from all configurations."""
    print("\n" + "=" * 80)
    print("PIPELINE INTEGRATION TEST RESULTS")
    print("=" * 80)

    # Summary table
    print(f"\n{'Config Name':<30} {'Status':<10} {'Bands':<8} {'Time (s)':<10} {'Top Influence':<15}")
    print("-" * 80)

    successful = 0
    for r in results:
        status = "✅ OK" if r["success"] else "❌ FAIL"
        n_bands = r.get("n_bands", "-")
        duration = f"{r.get('duration', 0):.1f}"
        top_inf = f"{r.get('top_influence', 0):.6f}" if r.get("top_influence") else "-"

        print(f"{r['config_name']:<30} {status:<10} {n_bands:<8} {duration:<10} {top_inf:<15}")

        if r["success"]:
            successful += 1

    print("-" * 80)
    print(f"Total: {successful}/{len(results)} configurations succeeded")

    # Detailed analysis of successful runs
    successful_results = [r for r in results if r["success"]]
    if successful_results:
        print("\n" + "=" * 80)
        print("DETAILED ANALYSIS")
        print("=" * 80)

        # Compare excitation distribution
        print("\nExcitation wavelength distribution (bands per excitation):")
        print(f"{'Config':<25}", end="")

        # Get all excitations
        all_excitations = set()
        for r in successful_results:
            if r.get("excitation_distribution"):
                all_excitations.update(r["excitation_distribution"].keys())
        all_excitations = sorted(all_excitations)

        for ex in all_excitations:
            print(f"{ex:>8}nm", end="")
        print()
        print("-" * (25 + len(all_excitations) * 10))

        for r in successful_results:
            print(f"{r['config_name']:<25}", end="")
            dist = r.get("excitation_distribution", {})
            for ex in all_excitations:
                count = dist.get(ex, 0)
                print(f"{count:>10}", end="")
            print()

        # Compare influence score statistics
        print("\nInfluence score statistics:")
        print(f"{'Config':<25} {'Min':<12} {'Max':<12} {'Mean':<12} {'Std':<12}")
        print("-" * 70)

        def fmt_stat(val: float) -> str:
            """Format stat value adaptively."""
            if abs(val) < 0.001 and val != 0:
                return f"{val:<12.2e}"
            return f"{val:<12.6f}"

        for r in successful_results:
            if r.get("influence_stats"):
                stats = r["influence_stats"]
                print(f"{r['config_name']:<25} "
                      f"{fmt_stat(stats['min'])} "
                      f"{fmt_stat(stats['max'])} "
                      f"{fmt_stat(stats['mean'])} "
                      f"{fmt_stat(stats['std'])}")

        # Top wavelengths comparison
        print("\nTop 5 wavelengths for each config:")
        print("-" * 80)

        for r in successful_results:
            print(f"\n{r['config_name']}:")
            if r.get("top_wavelengths"):
                for i, wl in enumerate(r["top_wavelengths"][:5], 1):
                    # Use adaptive formatting for influence scores
                    inf = wl['influence']
                    inf_str = f"{inf:.2e}" if abs(inf) < 0.001 and inf != 0 else f"{inf:.6f}"
                    print(f"  {i}. Ex={wl['excitation']}nm, Em={wl['emission']}nm, "
                          f"Influence={inf_str}")

    # Check result consistency
    print("\n" + "=" * 80)
    print("RESULT CONSISTENCY CHECK")
    print("=" * 80)

    if len(successful_results) >= 2:
        # Compare if different methods produce different results
        baseline = successful_results[0]
        print(f"\nComparing to baseline ({baseline['config_name']}):")

        for r in successful_results[1:]:
            if r.get("top_wavelengths") and baseline.get("top_wavelengths"):
                baseline_top = set(
                    (w["excitation"], w["emission"])
                    for w in baseline["top_wavelengths"][:10]
                )
                current_top = set(
                    (w["excitation"], w["emission"])
                    for w in r["top_wavelengths"][:10]
                )
                overlap = len(baseline_top & current_top)
                print(f"  {r['config_name']}: {overlap}/10 top bands overlap with baseline")

    print("\n" + "=" * 80)


def run_single_config(
    config_params: Dict[str, Any],
    data: SpectraData,
    output_base: Path,
    model_path: Path,
) -> Dict[str, Any]:
    """Run analysis with a single configuration using a pre-trained model."""
    config_name = config_params.pop("name")
    logger.info(f"\n{'=' * 60}")
    logger.info(f"Running config: {config_name}")
    logger.info(f"{'=' * 60}")

    result = {
        "config_name": config_name,
        "success": False,
        "error": None,
    }

    start_time = time.time()

    try:
        # Create output directory for this config
        output_dir = output_base / config_name
        output_dir.mkdir(parents=True, exist_ok=True)

        # Create config with shared model path
        config = Config(
            sample_name=f"Lichens_2_{config_name}",
            output_dir=output_dir,
            model_path=model_path,  # Use the pre-trained shared model
            device="cpu",  # Use CPU for consistency
            n_baseline_patches=20,  # Reduced for speed
            patch_size=32,
            save_tiff_layers=False,  # Skip for speed
            save_visualizations=False,  # Skip for speed
            **config_params,
        )

        # Create analyzer - it will load the pre-trained model
        analyzer = Analyzer(config)

        # Run fit (model will be loaded, not trained)
        analyzer.fit(data)

        # Get results
        wavelengths = analyzer.get_wavelengths()

        # Extract statistics
        result["success"] = True
        result["n_bands"] = len(wavelengths)
        result["duration"] = time.time() - start_time

        # Influence stats
        influences = [w.influence_score for w in wavelengths]
        result["influence_stats"] = {
            "min": float(np.min(influences)),
            "max": float(np.max(influences)),
            "mean": float(np.mean(influences)),
            "std": float(np.std(influences)),
        }
        result["top_influence"] = influences[0] if influences else 0

        # Excitation distribution
        ex_dist: Dict[float, int] = {}
        for w in wavelengths:
            ex = w.excitation_nm
            ex_dist[ex] = ex_dist.get(ex, 0) + 1
        result["excitation_distribution"] = ex_dist

        # Top wavelengths
        result["top_wavelengths"] = [
            {
                "excitation": w.excitation_nm,
                "emission": w.emission_nm,
                "influence": w.influence_score,
                "rank": w.rank,
            }
            for w in wavelengths[:10]
        ]

        # Save results
        analyzer.save_results(output_dir)

        logger.info(f"✅ Config {config_name} completed: {len(wavelengths)} bands selected")

    except Exception as e:
        result["error"] = str(e)
        result["duration"] = time.time() - start_time
        logger.error(f"❌ Config {config_name} failed: {e}")
        import traceback
        traceback.print_exc()

    return result


def train_shared_model(data: SpectraData, output_base: Path, num_epochs: int = 20) -> Path:
    """Train a single model to be shared across all configurations.

    Returns the path to the saved model weights.
    """
    print("\n" + "=" * 80)
    print("STEP 1: Training shared autoencoder model")
    print("=" * 80)

    model_path = output_base / "shared_model.pth"

    # Check if model already exists
    if model_path.exists():
        print(f"✅ Found existing model at {model_path}")
        return model_path

    print(f"Training with {num_epochs} epochs...")
    start_time = time.time()

    # Create a config just for training
    train_config = Config(
        sample_name="Lichens_2_model_training",
        output_dir=output_base / "model_training",
        model_path=model_path,
        device="cpu",
        n_baseline_patches=20,
        patch_size=32,
        n_bands_to_select=20,
        save_tiff_layers=False,
        save_visualizations=False,
    )

    # Create analyzer and train
    analyzer = Analyzer(train_config)

    # Patch training to use fewer epochs
    def fast_train():
        patched_train_new_model(analyzer, num_epochs=num_epochs)
    analyzer._train_new_model = fast_train

    # Run fit to train the model
    analyzer.fit(data)

    duration = time.time() - start_time
    print(f"✅ Model trained and saved to {model_path} ({duration:.1f}s)")

    return model_path


def main():
    """Run the full pipeline integration test."""
    print("=" * 80)
    print("SPECTRAL_SELECT FULL PIPELINE INTEGRATION TEST")
    print("=" * 80)
    print(f"Testing with 10 configurations, 20 epochs for model training")
    print()

    # Load data (using trusted pickle file from preprocessing)
    data_path = PROJECT_ROOT / "Data/processed/Lichens_2/temp_cropped/lichens_data_cropped.pkl"

    if not data_path.exists():
        print(f"❌ Data file not found: {data_path}")
        print("Please ensure the Lichens_2 dataset is preprocessed.")
        sys.exit(1)

    print(f"Loading data from: {data_path}")
    data = SpectraData.from_pickle(data_path)
    print(f"Data loaded: {data.n_excitations} excitations, spatial shape {data.spatial_shape}")
    print()

    # Setup output directory
    output_base = PROJECT_ROOT / "results/integration_test_results"
    output_base.mkdir(parents=True, exist_ok=True)
    print(f"Output directory: {output_base}")

    # STEP 1: Train model ONCE
    model_path = train_shared_model(data, output_base, num_epochs=20)

    # STEP 2: Run all configs using the shared model
    print("\n" + "=" * 80)
    print("STEP 2: Running 10 configurations with shared model")
    print("=" * 80)

    configs = get_test_configurations()
    print(f"Running {len(configs)} configurations...")

    # Run all configs
    results = []
    total_start = time.time()

    for i, config_params in enumerate(configs, 1):
        print(f"\n[{i}/{len(configs)}] ", end="")
        result = run_single_config(
            config_params.copy(),  # Copy to avoid modifying original
            data,
            output_base,
            model_path=model_path,  # Pass the shared model
        )
        results.append(result)

    total_duration = time.time() - total_start
    print(f"\n\nTotal execution time: {total_duration:.1f} seconds")

    # Evaluate results
    evaluate_results(results)

    # Final verdict
    successful = sum(1 for r in results if r["success"])
    print(f"\n{'=' * 80}")
    if successful == len(results):
        print("🎉 ALL CONFIGURATIONS PASSED - Pipeline integration verified!")
    elif successful > 0:
        print(f"⚠️  PARTIAL SUCCESS - {successful}/{len(results)} configurations worked")
    else:
        print("❌ ALL CONFIGURATIONS FAILED - Pipeline has issues!")
    print("=" * 80)

    return 0 if successful > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
